### ISSUE TITLE
Change Database, so it contains fewer files

### ISSUE THREAD

**Issue by PeterMakus** [PeterMakus/PyGLImER#30]
I need to limit the number of files in the DB (else, the GFZ won't allow me to have PyGLImER on their server). Haven't thought about any solution yet. The idea would be something like: Having one file for all RFs belonging to one computation, same for the rest of the DB.
Do you have any ideas/previous experience with this @lsawade ?

**Comment by PeterMakus** [comment]
> ```shell
> pip install --no-binary=h5py h5py
> ```

Alright. After a couple of hours of working on it, I actually managed to compile and install a working parallel hdf5 environment. For me, the guidelines above did not work (I needed to add a couple of things). I am just gonna outline what I did in case you ever run into similar problems.
1. Probably most importantly: In order for mpi4py to compile, one needs a newer version of hdf5 (at least 1.8).
2. Some additional parameters needed to be defined, see below:

# HDF5
```shell
### Install parallel HDF5
# Set variables
MPICC=$(which mpicc) # the most common one is mpicc
MPIF90=$(which mpif90) # I used mpif90

#  download HDF5
HDF5_DESTDIR=<Path/to/where/you/to/install/hdf5>
HDF5_LINK="https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.22/src/hdf5-1.8.22.tar.gz"
HDF5_DIR="${HDF5_DIR}/build"
    
# Get installation files
wget -O hdf5.tar.gz $HDF5_LINK
tar -xzvf hdf5.tar.gz --strip-components=1 -C $HDF5_DESTDIR 

# Change directory to adios directory
cd $HDF5_DESTIR

# Check whether a previous build exists.
if [ -d build ]; then
 rm -rf build
fi

# Make build directory
mkdir build

# Configuration
./configure --enable-shared --enable-parallel \
    --enable-fortran --enable-fortran2003 \
    --prefix=$HDF5_DIR CC=$MPICC FC=$MPIF90

# Make, check, and install
make -j
# make -j check  # not really necessary all the time
make -j install
```
# mpi4py
This was not quite as straight forward. Curiously enough. This did not except `mpicc` as option, I had to locate the binary file and fill in an absolute file path like so:
```shell
wheris mpicc
```
The output of this went to
```shell
MPICC=$(output of previous command)
pip install mpi4py
```

# h5py
```shell
export CC=$(which mpicc) # for me, mpicc
export HDF5_MPI="ON"
# The place where we installed our hdf5 1.8 or higher. Else it might access another non-parallel build
export HDF5_DIR="${HDF5DIR}/build" 
pip install --no-binary=h5py h5py
```

# pyasdf
Straight-forward (also possible with `conda install -c conda-forge pyasdf`)
```shell
pip install pyasdf
```

# Check whether all of this actually worked
```shell
python -c "import pyasdf; pyasdf.print_sys_info()"
```
The output of this should look somewhat like this:
```shell
pyasdf version 0.7.4
===============================================================================
CPython 3.8.8, compiler: GCC 7.3.0
Linux 5.8.0-48-generic 64bit
Machine: x86_64, Processor: x86_64 with 16 cores
===============================================================================
HDF5 version 1.8.22, h5py version: 3.2.1
MPI: Open MPI, version: 4.0.3, mpi4py version: 3.0.3
Parallel I/O support: True
Problematic multiprocessing: None
===============================================================================
Other_modules:
	dill: 0.3.3
	lxml: 4.6.3
	numpy: 1.20.2
	obspy: 1.2.2
	prov: 2.0.0
	scipy: 1.6.2
```
*Check the line that says  `Parallel I/O support` (has to be = True).*

I actually don't use this for PyGLImER right now but for a different project. Figured it would be useful to write it down nonetheless.

**Comment by lsawade** [comment]
The HDF5 link I provided is using HDF5 1.12 right?

**Comment by PeterMakus** [comment]
Yes!

**Comment by PeterMakus** [comment]
Today I tested whether it was possible to add custom data as waveforms to ``ASDF`` and it's not. So it looks like we will have to craft our own solution to write and read ``RFStream`` and ``RFTrace`` objects to hdf5/asdf files. So far I haven't thought of any smart solution though.

**Comment by lsawade** [comment]
checking out [obspyh5](https://github.com/trichter/obspyh5) again?

**Comment by PeterMakus** [comment]
I will create a homegrown hdf5 handler for receiver functions. I already did this for noise correlations and it works quite well + wasn't too much effort.

**Comment by lsawade** [comment]
> I will create a homegrown hdf5 handler for receiver functions. I already did this for noise correlations and it works quite well + wasn't too much effort.

Can you write down the procedure for that? I may be interested in this as well for my own project. 

---

Or it would be neat if some project could reconcile custom streams and traces, but I don't know if that make sense, I haven't looked into this myself

**Comment by PeterMakus** [comment]
Ok, there is an early version on the dev branch now. It's a little early to merge to master. But will keep you posted.

**Comment by PeterMakus** [comment]
Forgot one thing:
The processing needs to check, whether files are already processed (and!) if the files failed the QC scheme before. Else, we will have astronomical processing times every time we recompute.

**Comment by PeterMakus** [comment]
ok done. Hdf5 is still slower, but that is just due to additional reading overheads that become necessary.
