### ISSUE TITLE
Cross Section Tool using yet another KDTree

### ISSUE THREAD

**Issue by lsawade** [PeterMakus/PyGLImER#34]
# Cross Section Tool

Finally, I have an idea how to efficiently implement a cross section tool. See image below (description below image).

![IMG_0003](https://user-images.githubusercontent.com/23224303/114421044-e1b94000-9b82-11eb-979b-7a5b34be1635.jpg)

Given a line of points (blue line) along certain waypoints (solid dots), and a distance from the line, we can interpolate the points on the line using a KDTree that takes the line points as input, and the modified Shephard's method (using it already in meshslice, i.e. it's already coded up).

The first step will be similar to the Matlab cross section tool, by discarding stations that we don't need for the interpolation. Then, we find the distance to all the leftover CCPs from the line using the line's KDTree and the SphericalKDTree nearest neighbor interpolation. We do it for all depth's done. I will modify the `SphericalNN` from mesh slice in such a way that it can output the necessary arrays to interpolate data using multiplication, s.t. the distance computation is done once. OR I'll give int the necessary arrays as attributes/properties -- let's see, either way, I'll do it some time this week. Should be done in no time..

**Comment by PeterMakus** [comment]
Nice! But isn't that more or less what I suggested in our last meeting? :stuck_out_tongue: 

Just some minor points:
1. When using a KD-Tree, I don't think you need to discard any CCPs beforehand. The query points (i.e., CCPs) will just be disregarded if the distance is too high from the treepoints.
2. Again, no real need to do this for all depths. If you just use one point on the surface for each it is enough. The depths stay the same anyways and don't need to be interpolated.

Just my thoughts, let me know if I misunderstood something.

**Comment by lsawade** [comment]
> Nice! But isn't that more or less what I suggested in our last meeting? 😛

Maybe, I don't remember 😬

> 1. When using a KD-Tree, I don't think you need to discard any CCPs beforehand. The query points (i.e., CCPs) will just be disregarded if the distance is too high from the treepoints.

That is probably right, yeah, especially since the kdtree is already built..

> 2. Again, no real need to do this for all depths. If you just use one point on the surface for each it is enough. The depths stay the same anyways and don't need to be interpolated.

That's right. I only do it once. get the distance and weighting matrix and it should be done in no time ... Hopefully.

**Comment by lsawade** [comment]
Cross section tool and depth slice plotting are working. I just gotta bring some function from my library to pyglimer, and we are good to go. 

The section making is extremely fast, for both vertical and depth slices. It is fun to play with. I'll keep you posted

**Comment by lsawade** [comment]
Update was brought to pyglimer as part of #40.
