### ISSUE TITLE
Tutorial download not working

### ISSUE THREAD

**Issue by lsawade** [PeterMakus/PyGLImER#36]
Hi Peter,

I have been trying to to get the tutorial `00` to run without any luck, I think it may be related to #30 (`HDF5`). 

Let me know whether you can get it to run.

Cheers,

Lucas

**Comment by PeterMakus** [comment]
I assume you don't get any error message?

**Comment by PeterMakus** [comment]
Possible that I accidentally commented a line that should not be commented.

**Comment by lsawade** [comment]
Yeah no error messages

**Comment by lsawade** [comment]
I also tried using the `config.py` and `GLImER.py` without any luck.

**Comment by PeterMakus** [comment]
Well I don't know. It works for me, didn't have to change anything. Just to be clear once more: The problem is that you start the download and you don't get any waveforms?

**Comment by PeterMakus** [comment]
Ok, I found the bug(s) and fixed them.
Note that I will open a new unrelated issue, could you have a look at?
Also, let me know, whether it works now.
