### ISSUE TITLE
RAM overflow when writing hdf5 data

### ISSUE THREAD

**Issue by PeterMakus** [PeterMakus/PyGLImER#81]
### Symptom
When using `request.download()` with the parameter `format` set to `hdf5`, one will get an out-of-memory failure after a couple of days running. The used memory increases slowly and slowly.

### Where could the bug be located
Given the above conditions, I am pretty sure that the bug is in `pyglimer.database.asdf.writeraw` or `pyglimer.database.asdf.write_st`. Both of these are pretty compact functions and I don't really see where this could occur as I am overwriting my variables in each execution anyways (?), i.e., the functions are just completed and don't stay open.

### What I have tried so far
Deleting the variables `st` and `statxml` in both of the aforementioned functions. No success...

@lsawade , I don't know if you could have a quick look at the function just to see, whether I did some obvious mistake?

**Comment by lsawade** [comment]
@PeterMakus, I will take a long in a couple of days. Prepping submission for a manuscript right now (finally).

A thing that comes to mind is that event though you are deleting the reference to a variable you might not actually delete it from memory. I have seen that before with matplotlib axes. Especially ipython sometimes has difficulty to garbage collect correctly when references are kept to other objects. If it is in fact this problem, this may solve the issue:
```
a = 109283
a = None
```
instead of
```
del a
```

Here a quick ref from stackoverflow: [SOF manual garbage collection](https://stackoverflow.com/questions/1641717/manual-garbage-collection-in-python)

**Comment by PeterMakus** [comment]
Thanks for that. Did unfortunately not solve the problem. While doing that, I came to realise that the hdf5 download implementation is unsatisfyingly slow (a little unsure why - maybe it also has to do with this bug). For now, it still seems to be the more sensible option to download in mseed :( so that's an issue I will have to fix somehow.

**Comment by PeterMakus** [comment]
pretty sure it has to do with this here: https://github.com/SeismicData/pyasdf/issues/72

**Comment by PeterMakus** [comment]
Yup, after reading up on this. It all makes a lot of sense. The RAM is not overflowing, instead the whole event catalogue is read in each of the hdf5 files (I think). I don't think saving the events in the ASDF file is a good solution. Instead, we will probably have to go back to saving the Event Catalogue as one separate file again. I will come back to you once I've tested this

**Comment by PeterMakus** [comment]
#82 solves this issue.

Just so you understand what happened: Every time an event is added, ASDF checks whether the event is already in the file. To do that, it has to read the whole event catalogue in the file (often several thousand events). That needs a lot of RAM and takes a lot of time.
I haven't noticed that before as all the test-applications did only use one or two years of events.

In general, one has to be a bit careful with ASDF and HDF5 and make sure to use methods that only read the data's labels (equivalent to file names in a normal file system) rather than the actual dataset (unless one requires to do so). I fixed one place in the code where this was not done correctly (my bad).
